name: Deploy

# Controls when the workflow will run
'on':
  #triggers the workflow whenever a push is made to the main branch
  push:
    branches:
      - master
jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # install dependencies from yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: build app
        run: yarn build
      - name: deploy to production
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
